[workspace]
resolver = "2"
members = [
    "rustdb"
]
[workspace.package]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
bytes = "1.5"
tokio = "1.36"
thiserror = "1.0"
